--- Copyright 2021 Internet Corporation for Assigned Names and Numbers.
---
--- This Source Code Form is subject to the terms of the Mozilla Public
--- License, v. 2.0. If a copy of the MPL was not distributed with this
--- file, you can obtain one at https://mozilla.org/MPL/2.0/.
---
--- Developed by Sinodun IT (sinodun.com)
---
--- Info on nodes.
---
CREATE TABLE node_server (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  altname VARCHAR(255)
);

CREATE TABLE node_instance (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE node_city (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE node_country (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE node_region (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE node (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  altname VARCHAR(255),
  server_id INTEGER REFERENCES node_server(id),
  instance_id INTEGER REFERENCES node_instance(id),
  city_id INTEGER REFERENCES node_city(id),
  country_id INTEGER REFERENCES node_country(id),
  region_id INTEGER REFERENCES node_region(id),
  service_addr VARCHAR(40),
  flags INTEGER NOT NULL DEFAULT 0,

  UNIQUE(name, server_id)
);

---
--- Info on TLDs (Top Level Domains).
---
CREATE TABLE tld_type (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE tld (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  type_id INTEGER REFERENCES tld_type(id),
  ulabel VARCHAR(255)
);

---
--- Info on IANA registry types.
---
CREATE TABLE iana_registry (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE iana_value (
  id SERIAL PRIMARY KEY NOT NULL,
  registry_id INTEGER REFERENCES iana_registry(id),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  value INTEGER NOT NULL
);

---
--- Geolocation data points
---
CREATE TABLE geolocation (
  id INTEGER PRIMARY KEY NOT NULL,
  country_id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL
);

---
--- Server addresses,
---
--- Each address must be a string with an IPv6 address, as that's what
--- ClickHouse deals with, for example:
--- 2001:500:3::42 or  ::ffff:199.7.83.42
---
CREATE TABLE server_address (
  id SERIAL PRIMARY KEY NOT NULL,
  address VARCHAR(255) NOT NULL UNIQUE
);

---
--- Views with attributes expanded.
---
CREATE VIEW node_text
AS SELECT
  node.id AS node_id,
  node.name AS name,
  node_server.name AS server_name,
  node_instance.name AS instance_name,
  node_city.name AS city_name,
  node_country.name AS country_name,
  node_region.name AS region_name,
  node.flags AS flags
FROM node
INNER JOIN node_instance ON node_instance.id = node.instance_id
INNER JOIN node_server ON node_server.id = node.server_id
INNER JOIN node_city ON node_city.id = node.city_id
INNER JOIN node_country ON node_country.id = node.country_id
INNER JOIN node_region ON node_region.id = node.region_id;

CREATE VIEW tld_text
AS SELECT
  tld.name,
  tld_type.name AS tld_type,
  ulabel
FROM tld
JOIN tld_type ON tld_type.id = tld.type_id;

CREATE VIEW iana_text
AS SELECT
  iana_registry.name AS registry_name,
  iana_value.name AS value_name,
  iana_value.description AS value_description,
  iana_value.value as value
FROM iana_value
INNER JOIN iana_registry ON iana_registry.id = iana_value.registry_id;

---
--- Initial values for tlds.
---
INSERT INTO tld_type (name) VALUES
  ('Legacy-gTLD'),
  ('ccTLD'),
  ('New-gTLD');

INSERT INTO tld (name, type_id) VALUES
  ('cyou', 3),
  ('site', 3),
  ('chanel', 3),
  ('gent', 3),
  ('xn--mxtq1m', 3),
  ('ltda', 3),
  ('tattoo', 3),
  ('schmidt', 3),
  ('cipriani', 3),
  ('star', 3),
  ('bv', 2),
  ('mo', 2),
  ('xyz', 3),
  ('mz', 2),
  ('training', 3),
  ('kfh', 3),
  ('telefonica', 3),
  ('us', 2),
  ('style', 3),
  ('pg', 2),
  ('swiss', 3),
  ('xn--i1b6b1a6a2e', 3),
  ('spreadbetting', 3),
  ('ferrero', 3),
  ('bbc', 3),
  ('meet', 3),
  ('icbc', 3),
  ('trust', 3),
  ('ws', 2),
  ('weber', 3),
  ('pf', 2),
  ('gal', 3),
  ('cm', 2),
  ('download', 3),
  ('airtel', 3),
  ('quebec', 3),
  ('lt', 2),
  ('lawyer', 3),
  ('insurance', 3),
  ('xn--nqv7f', 3),
  ('paris', 3),
  ('bloomberg', 3),
  ('like', 3),
  ('dclk', 3),
  ('sd', 2),
  ('brother', 3),
  ('xn--vhquv', 3),
  ('np', 2),
  ('tips', 3),
  ('christmas', 3),
  ('xn--czru2d', 3),
  ('camp', 3),
  ('sfr', 3),
  ('chloe', 3),
  ('lifestyle', 3),
  ('technology', 3),
  ('degree', 3),
  ('st', 2),
  ('xn--eckvdtc9d', 3),
  ('xn--fiq64b', 3),
  ('xn--kput3i', 3),
  ('world', 3),
  ('caravan', 3),
  ('zuerich', 3),
  ('courses', 3),
  ('bradesco', 3),
  ('bm', 2),
  ('abogado', 3),
  ('goog', 3),
  ('boats', 3),
  ('domains', 3),
  ('xn--yfro4i67o', 2),
  ('mu', 2),
  ('page', 3),
  ('bentley', 3),
  ('wme', 3),
  ('sz', 2),
  ('design', 3),
  ('amica', 3),
  ('date', 3),
  ('vu', 2),
  ('bnpparibas', 3),
  ('support', 3),
  ('pictet', 3),
  ('ms', 2),
  ('se', 2),
  ('lupin', 3),
  ('nl', 2),
  ('ge', 2),
  ('bing', 3),
  ('km', 2),
  ('online', 3),
  ('singles', 3),
  ('xn--rhqv96g', 3),
  ('win', 3),
  ('center', 3),
  ('jaguar', 3),
  ('ci', 2),
  ('am', 2),
  ('wang', 3),
  ('wine', 3),
  ('hosting', 3),
  ('contractors', 3),
  ('xn--ses554g', 3),
  ('sew', 3),
  ('read', 3),
  ('nc', 2),
  ('codes', 3),
  ('ipiranga', 3),
  ('rentals', 3),
  ('eu', 2),
  ('express', 3),
  ('post', 1),
  ('wtc', 3),
  ('latrobe', 3),
  ('sk', 2),
  ('commbank', 3),
  ('xin', 3),
  ('vin', 3),
  ('florist', 3),
  ('bf', 2),
  ('reviews', 3),
  ('ma', 2),
  ('docs', 3),
  ('arpa', 1),
  ('kia', 3),
  ('py', 2),
  ('racing', 3),
  ('lu', 2),
  ('xn--vermgensberater-ctb', 3),
  ('jetzt', 3),
  ('panerai', 3),
  ('kh', 2),
  ('actor', 3),
  ('iwc', 3),
  ('wed', 3),
  ('xn--80adxhks', 3),
  ('xn--3ds443g', 3),
  ('soy', 3),
  ('gb', 2),
  ('fage', 3),
  ('auto', 3),
  ('democrat', 3),
  ('holdings', 3),
  ('oracle', 3),
  ('moi', 3),
  ('scot', 3),
  ('uk', 2),
  ('family', 3),
  ('man', 3),
  ('bharti', 3),
  ('jewelry', 3),
  ('mormon', 3),
  ('ai', 2),
  ('abb', 3),
  ('yodobashi', 3),
  ('vegas', 3),
  ('immo', 3),
  ('kpn', 3),
  ('qa', 2),
  ('xn--hxt814e', 3),
  ('ec', 2),
  ('gy', 2),
  ('ninja', 3),
  ('id', 2),
  ('abbott', 3),
  ('pk', 2),
  ('attorney', 3),
  ('condos', 3),
  ('feedback', 3),
  ('healthcare', 3),
  ('cv', 2),
  ('apple', 3),
  ('infiniti', 3),
  ('kitchen', 3),
  ('symantec', 3),
  ('srl', 3),
  ('academy', 3),
  ('fish', 3),
  ('travelers', 3),
  ('pt', 2),
  ('comsec', 3),
  ('gives', 3),
  ('schule', 3),
  ('beats', 3),
  ('axa', 3),
  ('jobs', 1),
  ('tokyo', 3),
  ('vg', 2),
  ('club', 3),
  ('voyage', 3),
  ('bingo', 3),
  ('ee', 2),
  ('furniture', 3),
  ('realty', 3),
  ('xn--vuq861b', 3),
  ('mr', 2),
  ('ru', 2),
  ('jcb', 3),
  ('voting', 3),
  ('theater', 3),
  ('tab', 3),
  ('engineering', 3),
  ('consulting', 3),
  ('help', 3),
  ('play', 3),
  ('casa', 3),
  ('xn--pgbs0dh', 2),
  ('hsbc', 3),
  ('cologne', 3),
  ('exchange', 3),
  ('engineer', 3),
  ('eat', 3),
  ('delivery', 3),
  ('farm', 3),
  ('wanggou', 3),
  ('airforce', 3),
  ('plumbing', 3),
  ('surf', 3),
  ('watch', 3),
  ('va', 2),
  ('wiki', 3),
  ('sr', 2),
  ('life', 3),
  ('legal', 3),
  ('xn--3e0b707e', 2),
  ('website', 3),
  ('xn--80ao21a', 2),
  ('gmx', 3),
  ('stcgroup', 3),
  ('sydney', 3),
  ('finance', 3),
  ('madrid', 3),
  ('gle', 3),
  ('lighting', 3),
  ('ls', 2),
  ('watches', 3),
  ('cx', 2),
  ('foo', 3),
  ('office', 3),
  ('cuisinella', 3),
  ('movie', 3),
  ('sky', 3),
  ('xn--flw351e', 3),
  ('vlaanderen', 3),
  ('tirol', 3),
  ('science', 3),
  ('virgin', 3),
  ('expert', 3),
  ('vodka', 3),
  ('montblanc', 3),
  ('bt', 2),
  ('vana', 3),
  ('fit', 3),
  ('info', 1),
  ('cartier', 3),
  ('canon', 3),
  ('edu', 1),
  ('how', 3),
  ('glass', 3),
  ('in', 2),
  ('moscow', 3),
  ('aarp', 3),
  ('house', 3),
  ('desi', 3),
  ('nexus', 3),
  ('bo', 2),
  ('ping', 3),
  ('il', 2),
  ('ie', 2),
  ('coach', 3),
  ('redstone', 3),
  ('events', 3),
  ('beer', 3),
  ('archi', 3),
  ('press', 3),
  ('dabur', 3),
  ('xerox', 3),
  ('shell', 3),
  ('hotmail', 3),
  ('study', 3),
  ('lv', 2),
  ('shoes', 3),
  ('lotto', 3),
  ('mm', 2),
  ('miami', 3),
  ('xn--6qq986b3xl', 3),
  ('ly', 2),
  ('red', 3),
  ('lacaixa', 3),
  ('cool', 3),
  ('tienda', 3),
  ('xn--lgbbat1ad8j', 2),
  ('xn--imr513n', 3),
  ('mv', 2),
  ('gh', 2),
  ('cloud', 3),
  ('sbs', 3),
  ('aquarelle', 3),
  ('theatre', 3),
  ('xn--mgbab2bd', 3),
  ('temasek', 3),
  ('group', 3),
  ('piaget', 3),
  ('dnp', 3),
  ('my', 2),
  ('cards', 3),
  ('moe', 3),
  ('doha', 3),
  ('xn--90a3ac', 2),
  ('xn--p1ai', 2),
  ('market', 3),
  ('okinawa', 3),
  ('live', 3),
  ('cafe', 3),
  ('fail', 3),
  ('xn--80aswg', 3),
  ('sandvik', 3),
  ('xn--1qqw23a', 3),
  ('neustar', 3),
  ('show', 3),
  ('xn--xhq521b', 3),
  ('mortgage', 3),
  ('sj', 2),
  ('do', 2),
  ('forex', 3),
  ('nadex', 3),
  ('community', 3),
  ('kinder', 3),
  ('international', 3),
  ('re', 2),
  ('gift', 3),
  ('dvag', 3),
  ('giving', 3),
  ('dev', 3),
  ('gl', 2),
  ('lat', 3),
  ('deals', 3),
  ('men', 3),
  ('rip', 3),
  ('xn--kcrx77d1x4a', 3),
  ('xn--p1acf', 3),
  ('catering', 3),
  ('today', 3),
  ('bs', 2),
  ('gifts', 3),
  ('sx', 2),
  ('sanofi', 3),
  ('graphics', 3),
  ('ibm', 3),
  ('xn--c2br7g', 3),
  ('pl', 2),
  ('uol', 3),
  ('to', 2),
  ('shia', 3),
  ('lincoln', 3),
  ('protection', 3),
  ('onl', 3),
  ('rent', 3),
  ('menu', 3),
  ('cleaning', 3),
  ('xn--mgbc0a9azcg', 2),
  ('foundation', 3),
  ('mov', 3),
  ('linde', 3),
  ('ne', 2),
  ('audi', 3),
  ('vet', 3),
  ('land', 3),
  ('xn--fiqs8s', 2),
  ('fitness', 3),
  ('spiegel', 3),
  ('emerck', 3),
  ('ice', 3),
  ('wtf', 3),
  ('firestone', 3),
  ('photos', 3),
  ('goldpoint', 3),
  ('barclaycard', 3),
  ('ricoh', 3),
  ('lamborghini', 3),
  ('buy', 3),
  ('aig', 3),
  ('restaurant', 3),
  ('gbiz', 3),
  ('at', 2),
  ('party', 3),
  ('fund', 3),
  ('mom', 3),
  ('zara', 3),
  ('sh', 2),
  ('bike', 3),
  ('ggee', 3),
  ('gallery', 3),
  ('fyi', 3),
  ('starhub', 3),
  ('gf', 2),
  ('reit', 3),
  ('discount', 3),
  ('crs', 3),
  ('xn--45q11c', 3),
  ('orange', 3),
  ('uy', 2),
  ('bms', 3),
  ('mini', 3),
  ('homes', 3),
  ('cu', 2),
  ('boo', 3),
  ('yandex', 3),
  ('azure', 3),
  ('xn--fzc2c9e2c', 2),
  ('bnl', 3),
  ('limo', 3),
  ('cc', 2),
  ('nf', 2),
  ('xn--kprw13d', 2),
  ('ads', 3),
  ('thd', 3),
  ('agency', 3),
  ('forsale', 3),
  ('tel', 1),
  ('med', 3),
  ('an', 2),
  ('barcelona', 3),
  ('supply', 3),
  ('aero', 1),
  ('gmail', 3),
  ('mba', 3),
  ('er', 2),
  ('ug', 2),
  ('playstation', 3),
  ('bid', 3),
  ('cal', 3),
  ('frl', 3),
  ('garden', 3),
  ('band', 3),
  ('nokia', 3),
  ('career', 3),
  ('nissan', 3),
  ('skype', 3),
  ('film', 3),
  ('suzuki', 3),
  ('futbol', 3),
  ('cash', 3),
  ('travel', 1),
  ('sb', 2),
  ('amsterdam', 3),
  ('xn--zfr164b', 3),
  ('dating', 3),
  ('genting', 3),
  ('trv', 3),
  ('cisco', 3),
  ('cheap', 3),
  ('financial', 3),
  ('ba', 2),
  ('xn--pssy2u', 3),
  ('tw', 2),
  ('limited', 3),
  ('obi', 3),
  ('scholarships', 3),
  ('brussels', 3),
  ('exposed', 3),
  ('lk', 2),
  ('properties', 3),
  ('sapo', 3),
  ('barclays', 3),
  ('republican', 3),
  ('xn--czrs0t', 3),
  ('toray', 3),
  ('wf', 2),
  ('ao', 2),
  ('stada', 3),
  ('xn--fhbei', 3),
  ('xn--mgbt3dhd', 3),
  ('ooo', 3),
  ('cars', 3),
  ('bible', 3),
  ('tg', 2),
  ('fashion', 3),
  ('de', 2),
  ('meo', 3),
  ('uno', 3),
  ('xn--mgberp4a5d4ar', 2),
  ('ky', 2),
  ('direct', 3),
  ('soccer', 3),
  ('krd', 3),
  ('nrw', 3),
  ('ck', 2),
  ('plus', 3),
  ('hitachi', 3),
  ('bmw', 3),
  ('clinic', 3),
  ('autos', 3),
  ('works', 3),
  ('kw', 2),
  ('one', 3),
  ('black', 3),
  ('chat', 3),
  ('fr', 2),
  ('security', 3),
  ('sale', 3),
  ('maison', 3),
  ('sc', 2),
  ('vista', 3),
  ('software', 3),
  ('markets', 3),
  ('money', 3),
  ('everbank', 3),
  ('ing', 3),
  ('ca', 2),
  ('buzz', 3),
  ('team', 3),
  ('bostik', 3),
  ('xn--clchc0ea0b2g2a9gcd', 2),
  ('gr', 2),
  ('broker', 3),
  ('construction', 3),
  ('tci', 3),
  ('mp', 2),
  ('wedding', 3),
  ('prof', 3),
  ('fly', 3),
  ('jot', 3),
  ('xn--3pxu8k', 3),
  ('vc', 2),
  ('youtube', 3),
  ('school', 3),
  ('bet', 3),
  ('xn--efvy88h', 3),
  ('motorcycles', 3),
  ('tf', 2),
  ('erni', 3),
  ('joburg', 3),
  ('university', 3),
  ('citic', 3),
  ('sy', 2),
  ('lasalle', 3),
  ('ubs', 3),
  ('landrover', 3),
  ('review', 3),
  ('bb', 2),
  ('xn--j1amh', 2),
  ('grainger', 3),
  ('pid', 3),
  ('coupons', 3),
  ('clubmed', 3),
  ('pn', 2),
  ('shriram', 3),
  ('dm', 2),
  ('jmp', 3),
  ('tennis', 3),
  ('yamaxun', 3),
  ('viva', 3),
  ('apartments', 3),
  ('bugatti', 3),
  ('mh', 2),
  ('tt', 2),
  ('place', 3),
  ('kred', 3),
  ('surgery', 3),
  ('rehab', 3),
  ('blue', 3),
  ('tj', 2),
  ('it', 2),
  ('epson', 3),
  ('whoswho', 3),
  ('stc', 3),
  ('horse', 3),
  ('gmo', 3),
  ('rodeo', 3),
  ('weir', 3),
  ('cw', 2),
  ('cr', 2),
  ('jprs', 3),
  ('xn--mgba3a3ejt', 3),
  ('careers', 3),
  ('arte', 3),
  ('accenture', 3),
  ('asia', 1),
  ('movistar', 3),
  ('is', 2),
  ('li', 2),
  ('tn', 2),
  ('cg', 2),
  ('lotte', 3),
  ('co', 2),
  ('frogans', 3),
  ('ryukyu', 3),
  ('fk', 2),
  ('verisign', 3),
  ('global', 3),
  ('cy', 2),
  ('bw', 2),
  ('cityeats', 3),
  ('ltd', 3),
  ('green', 3),
  ('bom', 3),
  ('name', 1),
  ('ist', 3),
  ('ifm', 3),
  ('college', 3),
  ('iinet', 3),
  ('su', 2),
  ('ax', 2),
  ('trading', 3),
  ('zero', 3),
  ('dj', 2),
  ('xn--kpry57d', 2),
  ('yokohama', 3),
  ('xn--d1alf', 2),
  ('ht', 2),
  ('bot', 3),
  ('football', 3),
  ('xn--55qx5d', 3),
  ('ng', 2),
  ('ski', 3),
  ('dental', 3),
  ('gea', 3),
  ('management', 3),
  ('budapest', 3),
  ('osaka', 3),
  ('icu', 3),
  ('statoil', 3),
  ('vip', 3),
  ('ye', 2),
  ('ren', 3),
  ('villas', 3),
  ('mobily', 3),
  ('haus', 3),
  ('ph', 2),
  ('dz', 2),
  ('xn--t60b56a', 3),
  ('xn--wgbl6a', 2),
  ('berlin', 3),
  ('email', 3),
  ('google', 3),
  ('boehringer', 3),
  ('mc', 2),
  ('fairwinds', 3),
  ('analytics', 3),
  ('honda', 3),
  ('loans', 3),
  ('mma', 3),
  ('prod', 3),
  ('ro', 2),
  ('casino', 3),
  ('hu', 2),
  ('by', 2),
  ('tatar', 3),
  ('cricket', 3),
  ('int', 1),
  ('marketing', 3),
  ('pin', 3),
  ('th', 2),
  ('fi', 2),
  ('kg', 2),
  ('ceo', 3),
  ('jm', 2),
  ('audio', 3),
  ('xbox', 3),
  ('yt', 2),
  ('luxe', 3),
  ('industries', 3),
  ('datsun', 3),
  ('leclerc', 3),
  ('au', 2),
  ('xn--45brj9c', 2),
  ('sohu', 3),
  ('al', 2),
  ('app', 3),
  ('xn--90ais', 2),
  ('gi', 2),
  ('bridgestone', 3),
  ('si', 2),
  ('reisen', 3),
  ('xn--nyqy26a', 3),
  ('salon', 3),
  ('sony', 3),
  ('host', 3),
  ('accountant', 3),
  ('build', 3),
  ('capital', 3),
  ('me', 2),
  ('istanbul', 3),
  ('mw', 2),
  ('gucci', 3),
  ('dad', 3),
  ('equipment', 3),
  ('mt', 2),
  ('rsvp', 3),
  ('nico', 3),
  ('xn--4gbrim', 3),
  ('sn', 2),
  ('gm', 2),
  ('mn', 2),
  ('xn--9et52u', 3),
  ('digital', 3),
  ('flights', 3),
  ('gripe', 3),
  ('xn--jlq61u9w7b', 3),
  ('eus', 3),
  ('lixil', 3),
  ('sexy', 3),
  ('mango', 3),
  ('productions', 3),
  ('xn--node', 2),
  ('bayern', 3),
  ('city', 3),
  ('xn--q9jyb4c', 3),
  ('im', 2),
  ('mk', 2),
  ('builders', 3),
  ('xn--estv75g', 3),
  ('xn--mgbayh7gpa', 2),
  ('poker', 3),
  ('earth', 3),
  ('photography', 3),
  ('gq', 2),
  ('windows', 3),
  ('london', 3),
  ('gs', 2),
  ('ve', 2),
  ('nagoya', 3),
  ('xn--6frz82g', 3),
  ('mg', 2),
  ('social', 3),
  ('kn', 2),
  ('cbn', 3),
  ('ntt', 3),
  ('homedepot', 3),
  ('xn--o3cw4h', 2),
  ('new', 3),
  ('tools', 3),
  ('ventures', 3),
  ('loan', 3),
  ('tickets', 3),
  ('pink', 3),
  ('country', 3),
  ('organic', 3),
  ('vote', 3),
  ('tc', 2),
  ('coffee', 3),
  ('za', 2),
  ('xn--gecrj9c', 2),
  ('reise', 3),
  ('xn--30rr7y', 3),
  ('williamhill', 3),
  ('bbva', 3),
  ('je', 2),
  ('coop', 1),
  ('pro', 1),
  ('sucks', 3),
  ('br', 2),
  ('travelersinsurance', 3),
  ('call', 3),
  ('scb', 3),
  ('pa', 2),
  ('mx', 2),
  ('bzh', 3),
  ('sm', 2),
  ('xn--nqv7fs00ema', 3),
  ('auction', 3),
  ('army', 3),
  ('repair', 3),
  ('game', 3),
  ('irish', 3),
  ('cfa', 3),
  ('stockholm', 3),
  ('lc', 2),
  ('xn--czr694b', 3),
  ('space', 3),
  ('netbank', 3),
  ('xn--pbt977c', 3),
  ('guru', 3),
  ('cooking', 3),
  ('bn', 2),
  ('navy', 3),
  ('xn--80asehdb', 3),
  ('care', 3),
  ('zw', 2),
  ('komatsu', 3),
  ('got', 3),
  ('lr', 2),
  ('org', 1),
  ('dog', 3),
  ('cruises', 3),
  ('nowruz', 3),
  ('be', 2),
  ('enterprises', 3),
  ('sg', 2),
  ('broadway', 3),
  ('nyc', 3),
  ('ruhr', 3),
  ('holiday', 3),
  ('xn--mgbbh1a71e', 2),
  ('ink', 3),
  ('wales', 3),
  ('ni', 2),
  ('pharmacy', 3),
  ('gdn', 3),
  ('ac', 2),
  ('gw', 2),
  ('hk', 2),
  ('gop', 3),
  ('xn--mk1bu44c', 3),
  ('rocks', 3),
  ('pics', 3),
  ('xn--wgbh1c', 2),
  ('xn--d1acj3b', 3),
  ('cfd', 3),
  ('seven', 3),
  ('tech', 3),
  ('ovh', 3),
  ('aq', 2),
  ('chrome', 3),
  ('creditcard', 3),
  ('toyota', 3),
  ('trade', 3),
  ('hangout', 3),
  ('es', 2),
  ('pohl', 3),
  ('xn--qcka1pmc', 3),
  ('hoteles', 3),
  ('cancerresearch', 3),
  ('goo', 3),
  ('rest', 3),
  ('bi', 2),
  ('luxury', 3),
  ('zm', 2),
  ('author', 3),
  ('channel', 3),
  ('hamburg', 3),
  ('sl', 2),
  ('doosan', 3),
  ('partners', 3),
  ('bargains', 3),
  ('voto', 3),
  ('et', 2),
  ('seek', 3),
  ('porn', 3),
  ('here', 3),
  ('gold', 3),
  ('scor', 3),
  ('news', 3),
  ('solar', 3),
  ('blackfriday', 3),
  ('om', 2),
  ('ki', 2),
  ('mil', 1),
  ('ua', 2),
  ('pub', 3),
  ('day', 3),
  ('saxo', 3),
  ('vn', 2),
  ('xn--11b4c3d', 3),
  ('otsuka', 3),
  ('click', 3),
  ('realtor', 3),
  ('supplies', 3),
  ('camera', 3),
  ('meme', 3),
  ('lancaster', 3),
  ('java', 3),
  ('ch', 2),
  ('mtr', 3),
  ('xn--xkc2dl3a5ee0h', 2),
  ('rich', 3),
  ('guide', 3),
  ('xn--xkc2al3hye2a', 2),
  ('ps', 2),
  ('xn--mgbb9fbpob', 3),
  ('koeln', 3),
  ('bar', 3),
  ('xn--mgbaam7a8h', 2),
  ('gn', 2),
  ('contact', 3),
  ('xn--fiqz9s', 2),
  ('la', 2),
  ('sakura', 3),
  ('business', 3),
  ('cl', 2),
  ('circle', 3),
  ('sener', 3),
  ('taipei', 3),
  ('tatamotors', 3),
  ('hiv', 3),
  ('kiwi', 3),
  ('network', 3),
  ('jp', 2),
  ('xn--kpu716f', 3),
  ('guitars', 3),
  ('swatch', 3),
  ('photo', 3),
  ('book', 3),
  ('bg', 2),
  ('fan', 3),
  ('ong', 3),
  ('xn--ogbpf8fl', 2),
  ('pictures', 3),
  ('jlc', 3),
  ('systems', 3),
  ('gt', 2),
  ('fj', 2),
  ('diamonds', 3),
  ('pars', 3),
  ('hiphop', 3),
  ('mobi', 1),
  ('tm', 2),
  ('melbourne', 3),
  ('sharp', 3),
  ('xn--fpcrj9c3d', 2),
  ('delta', 3),
  ('sandvikcoromant', 3),
  ('best', 3),
  ('fishing', 3),
  ('eurovision', 3),
  ('storage', 3),
  ('museum', 1),
  ('bcn', 3),
  ('xn--ygbi2ammx', 2),
  ('hermes', 3),
  ('sa', 2),
  ('toshiba', 3),
  ('accountants', 3),
  ('sex', 3),
  ('tz', 2),
  ('law', 3),
  ('rocher', 3),
  ('church', 3),
  ('sas', 3),
  ('tv', 2),
  ('uz', 2),
  ('globo', 3),
  ('ngo', 3),
  ('pw', 2),
  ('xn--fiq228c5hs', 3),
  ('mtn', 3),
  ('hyundai', 3),
  ('studio', 3),
  ('lease', 3),
  ('adult', 3),
  ('bh', 2),
  ('xn--cg4bki', 3),
  ('hm', 2),
  ('ke', 2),
  ('run', 3),
  ('samsung', 3),
  ('firmdale', 3),
  ('aramco', 3),
  ('nu', 2),
  ('hr', 2),
  ('toys', 3),
  ('joy', 3),
  ('sca', 3),
  ('lol', 3),
  ('xn--vermgensberatung-pwb', 3),
  ('ag', 2),
  ('zone', 3),
  ('cymru', 3),
  ('saarland', 3),
  ('tushu', 3),
  ('capetown', 3),
  ('sv', 2),
  ('fm', 2),
  ('xn--y9a3aq', 3),
  ('cn', 2),
  ('xn--c1avg', 3),
  ('cz', 2),
  ('cba', 3),
  ('fo', 2),
  ('sarl', 3),
  ('taxi', 3),
  ('pet', 3),
  ('property', 3),
  ('so', 2),
  ('car', 3),
  ('kyoto', 3),
  ('gov', 1),
  ('tours', 3),
  ('nec', 3),
  ('liaison', 3),
  ('parts', 3),
  ('xperia', 3),
  ('aw', 2),
  ('sap', 3),
  ('xn--s9brj9c', 2),
  ('rw', 2),
  ('drive', 3),
  ('na', 2),
  ('norton', 3),
  ('cf', 2),
  ('kaufen', 3),
  ('biz', 1),
  ('bio', 3),
  ('xn--mgba3a4f16a', 2),
  ('xn--3bst00m', 3),
  ('bond', 3),
  ('yachts', 3),
  ('io', 2),
  ('ad', 2),
  ('nr', 2),
  ('vacations', 3),
  ('forum', 3),
  ('viajes', 3),
  ('gp', 2),
  ('versicherung', 3),
  ('clothing', 3),
  ('nra', 3),
  ('creditunion', 3),
  ('fans', 3),
  ('immobilien', 3),
  ('aaa', 3),
  ('alsace', 3),
  ('diet', 3),
  ('flsmidth', 3),
  ('gg', 2),
  ('fast', 3),
  ('praxi', 3),
  ('net', 1),
  ('moda', 3),
  ('mutuelle', 3),
  ('computer', 3),
  ('safe', 3),
  ('work', 3),
  ('shiksha', 3),
  ('xn--42c2d9a', 3),
  ('boutique', 3),
  ('cab', 3),
  ('report', 3),
  ('pe', 2),
  ('cern', 3),
  ('az', 2),
  ('guge', 3),
  ('vistaprint', 3),
  ('walter', 3),
  ('smile', 3),
  ('tl', 2),
  ('final', 3),
  ('aco', 3),
  ('qpon', 3),
  ('xn--tckwe', 3),
  ('eg', 2),
  ('company', 3),
  ('services', 3),
  ('itau', 3),
  ('tires', 3),
  ('esq', 3),
  ('faith', 3),
  ('xn--l1acc', 2),
  ('pm', 2),
  ('lds', 3),
  ('aeg', 3),
  ('tui', 3),
  ('nhk', 3),
  ('corsica', 3),
  ('jll', 3),
  ('active', 3),
  ('dance', 3),
  ('tk', 2),
  ('afl', 3),
  ('schwarz', 3),
  ('directory', 3),
  ('xn--ngbe9e0a', 3),
  ('rwe', 3),
  ('omega', 3),
  ('ga', 2),
  ('ml', 2),
  ('dentist', 3),
  ('bz', 2),
  ('lidl', 3),
  ('associates', 3),
  ('town', 3),
  ('md', 2),
  ('credit', 3),
  ('hockey', 3),
  ('ford', 3),
  ('zip', 3),
  ('jo', 2),
  ('love', 3),
  ('rs', 2),
  ('philips', 3),
  ('microsoft', 3),
  ('dell', 3),
  ('yoga', 3),
  ('lexus', 3),
  ('solutions', 3),
  ('golf', 3),
  ('room', 3),
  ('rio', 3),
  ('tr', 2),
  ('maif', 3),
  ('xn--mgbpl2fh', 3),
  ('xn--fjq720a', 3),
  ('bj', 2),
  ('lgbt', 3),
  ('lb', 2),
  ('cat', 1),
  ('xn--io0a7i', 3),
  ('kz', 2),
  ('mq', 2),
  ('media', 3),
  ('td', 2),
  ('iq', 2),
  ('cd', 2),
  ('gratis', 3),
  ('crown', 3),
  ('hn', 2),
  ('recipes', 3),
  ('durban', 3),
  ('sncf', 1),
  ('top', 3),
  ('bauhaus', 3),
  ('energy', 3),
  ('vision', 3),
  ('claims', 3),
  ('flowers', 3),
  ('pizza', 3),
  ('video', 3),
  ('bd', 2),
  ('af', 2),
  ('no', 2),
  ('estate', 3),
  ('dk', 2),
  ('nz', 2),
  ('redumbrella', 3),
  ('insure', 3),
  ('xn--b4w605ferd', 3),
  ('seat', 3),
  ('webcam', 3),
  ('boots', 3),
  ('xn--9dbq2a', 3),
  ('xn--mgbx4cd0ab', 2),
  ('ae', 2),
  ('institute', 3),
  ('pr', 2),
  ('memorial', 3),
  ('com', 1),
  ('kddi', 3),
  ('allfinanz', 3),
  ('juegos', 3),
  ('gd', 2),
  ('monash', 3),
  ('investments', 3),
  ('xn--j6w193g', 2),
  ('gu', 2),
  ('xn--55qw42g', 3),
  ('kr', 2),
  ('xn--mgb9awbf', 2),
  ('xn--ngbc5azd', 3),
  ('ceb', 3),
  ('bank', 3),
  ('vi', 2),
  ('physio', 3),
  ('kim', 3),
  ('ir', 2),
  ('tax', 3),
  ('link', 3),
  ('as', 2),
  ('marriott', 3),
  ('android', 3),
  ('csc', 3),
  ('ar', 2),
  ('mtpc', 3),
  ('xxx', 1),
  ('xn--h2brj9c', 2),
  ('education', 3),
  ('wien', 3),
  ('kp', 2),
  ('xn--j1aef', 3),
  ('abarth', 3),
  ('abbvie', 3),
  ('abc', 3),
  ('able', 3),
  ('abudhabi', 3),
  ('adac', 3),
  ('aetna', 3),
  ('afamilycompany', 3),
  ('africa', 3),
  ('agakhan', 3),
  ('aigo', 3),
  ('airbus', 3),
  ('akdn', 3),
  ('alfaromeo', 3),
  ('alibaba', 3),
  ('alipay', 3),
  ('allstate', 3),
  ('ally', 3),
  ('alstom', 3),
  ('americanexpress', 3),
  ('americanfamily', 3),
  ('amex', 3),
  ('amfam', 3),
  ('anquan', 3),
  ('anz', 3),
  ('aol', 3),
  ('arab', 3),
  ('art', 3),
  ('asda', 3),
  ('athleta', 3),
  ('audible', 3),
  ('auspost', 3),
  ('avianca', 3),
  ('aws', 3),
  ('baby', 3),
  ('baidu', 3),
  ('banamex', 3),
  ('bananarepublic', 3),
  ('barefoot', 3),
  ('baseball', 3),
  ('basketball', 3),
  ('bbt', 3),
  ('bcg', 3),
  ('beauty', 3),
  ('bestbuy', 3),
  ('blanco', 3),
  ('blockbuster', 3),
  ('blog', 3),
  ('bofa', 3),
  ('booking', 3),
  ('bosch', 3),
  ('boston', 3),
  ('box', 3),
  ('calvinklein', 3),
  ('cam', 3),
  ('capitalone', 3),
  ('case', 3),
  ('caseih', 3),
  ('catholic', 3),
  ('cbre', 3),
  ('cbs', 3),
  ('chase', 3),
  ('chintai', 3),
  ('chrysler', 3),
  ('citadel', 3),
  ('citi', 3),
  ('clinique', 3),
  ('comcast', 3),
  ('compare', 3),
  ('cookingchannel', 3),
  ('coupon', 3),
  ('cruise', 3),
  ('data', 3),
  ('dds', 3),
  ('deal', 3),
  ('dealer', 3),
  ('deloitte', 3),
  ('dhl', 3),
  ('discover', 3),
  ('dish', 3),
  ('diy', 3),
  ('doctor', 3),
  ('dodge', 3),
  ('dot', 3),
  ('dtv', 3),
  ('dubai', 3),
  ('duck', 3),
  ('dunlop', 3),
  ('duns', 3),
  ('dupont', 3),
  ('dvr', 3),
  ('eco', 3),
  ('edeka', 3),
  ('epost', 3),
  ('ericsson', 3),
  ('esurance', 3),
  ('etisalat', 3),
  ('extraspace', 3),
  ('farmers', 3),
  ('fedex', 3),
  ('ferrari', 3),
  ('fiat', 3),
  ('fidelity', 3),
  ('fido', 3),
  ('fire', 3),
  ('flickr', 3),
  ('flir', 3),
  ('food', 3),
  ('foodnetwork', 3),
  ('fox', 3),
  ('free', 3),
  ('fresenius', 3),
  ('frontdoor', 3),
  ('frontier', 3),
  ('ftr', 3),
  ('fujitsu', 3),
  ('fujixerox', 3),
  ('fun', 3),
  ('gallo', 3),
  ('gallup', 3),
  ('games', 3),
  ('gap', 3),
  ('george', 3),
  ('glade', 3),
  ('gmbh', 3),
  ('godaddy', 3),
  ('goodhands', 3),
  ('goodyear', 3),
  ('grocery', 3),
  ('guardian', 3),
  ('hair', 3),
  ('hbo', 3),
  ('hdfc', 3),
  ('hdfcbank', 3),
  ('health', 3),
  ('helsinki', 3),
  ('hgtv', 3),
  ('hisamitsu', 3),
  ('hkt', 3),
  ('homegoods', 3),
  ('homesense', 3),
  ('honeywell', 3),
  ('hospital', 3),
  ('hot', 3),
  ('hotels', 3),
  ('htc', 3),
  ('hughes', 3),
  ('hyatt', 3),
  ('ieee', 3),
  ('ikano', 3),
  ('imamat', 3),
  ('imdb', 3),
  ('intel', 3),
  ('intuit', 3),
  ('iselect', 3),
  ('ismaili', 3),
  ('itv', 3),
  ('iveco', 3),
  ('jcp', 3),
  ('jeep', 3),
  ('jio', 3),
  ('jnj', 3),
  ('jpmorgan', 3),
  ('juniper', 3),
  ('kerryhotels', 3),
  ('kerrylogistics', 3),
  ('kerryproperties', 3),
  ('kindle', 3),
  ('kosher', 3),
  ('kpmg', 3),
  ('kuokgroup', 3),
  ('ladbrokes', 3),
  ('lamer', 3),
  ('lancia', 3),
  ('lancome', 3),
  ('lanxess', 3),
  ('latino', 3),
  ('lefrak', 3),
  ('lego', 3),
  ('lifeinsurance', 3),
  ('lilly', 3),
  ('lipsy', 3),
  ('living', 3),
  ('locker', 3),
  ('locus', 3),
  ('loft', 3),
  ('lpl', 3),
  ('lplfinancial', 3),
  ('lundbeck', 3),
  ('macys', 3),
  ('makeup', 3),
  ('map', 3),
  ('marshalls', 3),
  ('maserati', 3),
  ('mattel', 3),
  ('mcd', 3),
  ('mcdonalds', 3),
  ('mckinsey', 3),
  ('merckmsd', 3),
  ('metlife', 3),
  ('mint', 3),
  ('mit', 3),
  ('mitsubishi', 3),
  ('mlb', 3),
  ('mls', 3),
  ('mobile', 3),
  ('monster', 3),
  ('mopar', 3),
  ('moto', 3),
  ('msd', 3),
  ('mutual', 3),
  ('nab', 3),
  ('nationwide', 3),
  ('natura', 3),
  ('nba', 3),
  ('netflix', 3),
  ('newholland', 3),
  ('next', 3),
  ('nextdirect', 3),
  ('nfl', 3),
  ('nike', 3),
  ('nikon', 3),
  ('nissay', 3),
  ('northwesternmutual', 3),
  ('now', 3),
  ('nowtv', 3),
  ('observer', 3),
  ('off', 3),
  ('olayan', 3),
  ('olayangroup', 3),
  ('oldnavy', 3),
  ('ollo', 3),
  ('onyourside', 3),
  ('open', 3),
  ('origins', 3),
  ('ott', 3),
  ('pamperedchef', 3),
  ('panasonic', 3),
  ('passagens', 3),
  ('pay', 3),
  ('pccw', 3),
  ('pfizer', 3),
  ('phd', 3),
  ('phone', 3),
  ('pioneer', 3),
  ('pnc', 3),
  ('politie', 3),
  ('pramerica', 3),
  ('prime', 3),
  ('progressive', 3),
  ('promo', 3),
  ('pru', 3),
  ('prudential', 3),
  ('pwc', 3),
  ('quest', 3),
  ('qvc', 3),
  ('radio', 3),
  ('raid', 3),
  ('realestate', 3),
  ('reliance', 3),
  ('rexroth', 3),
  ('richardli', 3),
  ('rightathome', 3),
  ('ril', 3),
  ('rmit', 3),
  ('rogers', 3),
  ('rugby', 3),
  ('safety', 3),
  ('samsclub', 3),
  ('save', 3),
  ('sbi', 3),
  ('schaeffler', 3),
  ('scjohnson', 3),
  ('search', 3),
  ('secure', 3),
  ('select', 3),
  ('ses', 3),
  ('shangrila', 3),
  ('shaw', 3),
  ('shop', 3),
  ('shopping', 3),
  ('shouji', 3),
  ('showtime', 3),
  ('silk', 3),
  ('sina', 3),
  ('skin', 3),
  ('sling', 3),
  ('smart', 3),
  ('softbank', 3),
  ('song', 3),
  ('spot', 3),
  ('srt', 3),
  ('staples', 3),
  ('statebank', 3),
  ('statefarm', 3),
  ('store', 3),
  ('stream', 3),
  ('swiftcover', 3),
  ('talk', 3),
  ('taobao', 3),
  ('target', 3),
  ('tdk', 3),
  ('telecity', 3),
  ('teva', 3),
  ('tiaa', 3),
  ('tiffany', 3),
  ('tjmaxx', 3),
  ('tjx', 3),
  ('tkmaxx', 3),
  ('tmall', 3),
  ('total', 3),
  ('travelchannel', 3),
  ('tube', 3),
  ('tunes', 3),
  ('tvs', 3),
  ('ubank', 3),
  ('uconnect', 3),
  ('unicom', 3),
  ('ups', 3),
  ('vanguard', 3),
  ('vig', 3),
  ('viking', 3),
  ('visa', 3),
  ('vivo', 3),
  ('volkswagen', 3),
  ('volvo', 3),
  ('vuelos', 3),
  ('walmart', 3),
  ('warman', 3),
  ('weather', 3),
  ('weatherchannel', 3),
  ('weibo', 3),
  ('winners', 3),
  ('wolterskluwer', 3),
  ('woodside', 3),
  ('wow', 3),
  ('xfinity', 3),
  ('xihuan', 3),
  ('xn--1ck2e1b', 3),
  ('xn--2scrj9c', 3),
  ('xn--3hcrj9c', 3),
  ('xn--3oq18vl8pn36a', 3),
  ('xn--45br5cyl', 3),
  ('xn--5su34j936bgsg', 3),
  ('xn--5tzm5g', 3),
  ('xn--80aqecdr1a', 3),
  ('xn--8y0a063a', 3),
  ('xn--9krt00a', 3),
  ('xn--bck1b9a5dre4c', 3),
  ('xn--cck2b3b', 3),
  ('xn--e1a4c', 3),
  ('xn--fct429k', 3),
  ('xn--fzys8d69uvgm', 3),
  ('xn--g2xx48c', 3),
  ('xn--gckr3f0f', 3),
  ('xn--gk3at1e', 3),
  ('xn--h2breg3eve', 3),
  ('xn--h2brj9c8c', 3),
  ('xn--jvr189m', 3),
  ('xn--mgba7c0bbn0a', 3),
  ('xn--mgbaakc7dvf', 3),
  ('xn--mgbai9azgqp6j', 3),
  ('xn--mgbbh1a', 3),
  ('xn--mgbca7dzdo', 3),
  ('xn--mgbgu82a', 3),
  ('xn--mgbi4ecexp', 3),
  ('xn--ngbrx', 3),
  ('xn--rovu88b', 3),
  ('xn--rvc1e0am3e', 3),
  ('xn--tiq49xqyj', 3),
  ('xn--unup4y', 3),
  ('xn--w4r85el8fhu5dnra', 3),
  ('xn--w4rs40l', 3),
  ('yahoo', 3),
  ('you', 3),
  ('yun', 3),
  ('zappos', 3),
  ('zippo', 3);

---
--- Set IDN ccTLDs as such.
---
UPDATE tld SET type_id = 2 WHERE name IN (
  'xn--2scrj9c',
  'xn--3e0b707e',
  'xn--3hcrj9c',
  'xn--45br5cyl',
  'xn--45brj9c',
  'xn--80ao21a',
  'xn--90a3ac',
  'xn--90ais',
  'xn--clchc0ea0b2g2a9gcd',
  'xn--d1alf',
  'xn--e1a4c',
  'xn--fiqs8s',
  'xn--fiqz9s',
  'xn--fpcrj9c3d',
  'xn--fzc2c9e2c',
  'xn--gecrj9c',
  'xn--h2breg3eve',
  'xn--h2brj9c',
  'xn--h2brj9c8c',
  'xn--j1amh',
  'xn--j6w193g',
  'xn--kprw13d',
  'xn--kpry57d',
  'xn--l1acc',
  'xn--lgbbat1ad8j',
  'xn--mgb9awbf',
  'xn--mgba3a4f16a',
  'xn--mgbaam7a8h',
  'xn--mgbai9azgqp6j',
  'xn--mgbayh7gpa',
  'xn--mgbbh1a',
  'xn--mgbbh1a71e',
  'xn--mgbc0a9azcg',
  'xn--mgberp4a5d4ar',
  'xn--mgbgu82a',
  'xn--mgbpl2fh',
  'xn--mgbx4cd0ab',
  'xn--node',
  'xn--o3cw4h',
  'xn--ogbpf8fl',
  'xn--p1ai',
  'xn--pgbs0dh',
  'xn--rvc1e0am3e',
  'xn--s9brj9c',
  'xn--wgbh1c',
  'xn--wgbl6a',
  'xn--xkc2al3hye2a',
  'xn--xkc2dl3a5ee0h',
  'xn--y9a3aq',
  'xn--yfro4i67o',
  'xn--ygbi2ammx'
);

---
--- Initial values for IANA registry types.
---

INSERT INTO iana_registry (name) VALUES
  ('QTYPE'),
  ('DNSSEC QTYPE'),
  ('CLASS'),
  ('IP'),
  ('OPCODE'),
  ('RCODE'),
  ('EDNS0 Option');

INSERT INTO iana_value (registry_id, value, name, description) VALUES
  (4, 1, 'ICMP', 'Internet Control Message'),
  (4, 6, 'TCP', 'Transmission Control'),
  (4, 17, 'UDP', 'User Datagram'),
  (4, 58, 'IPv6-ICMP', 'ICMP for IPv6'),
  (3, 0, 'Reserved', 'Reserved'),
  (3, 1, 'IN', 'Internet'),
  (3, 2, 'Unassigned', 'Unassigned'),
  (3, 3, 'CH', 'Chaos'),
  (3, 4, 'HS', 'Hesiod'),
  (3, 254, 'NONE', 'QCLASS NONE'),
  (3, 255, 'ANY', 'QCLASS *'),
  (3, 65535, 'Reserved', 'Reserved'),
  (1, 1, 'A', 'a host address'),
  (1, 2, 'NS', 'an authoritative name server'),
  (1, 3, 'MD', 'a mail destination (OBSOLETE - use MX)'),
  (1, 4, 'MF', 'a mail forwarder (OBSOLETE - use MX)'),
  (1, 5, 'CNAME', 'the canonical name for an alias'),
  (1, 6, 'SOA', 'marks the start of a zone of authority'),
  (1, 7, 'MB', 'a mailbox domain name (EXPERIMENTAL)'),
  (1, 8, 'MG', 'a mail group member (EXPERIMENTAL)'),
  (1, 9, 'MR', 'a mail rename domain name (EXPERIMENTAL)'),
  (1, 10, 'NULL', 'a null RR (EXPERIMENTAL)'),
  (1, 11, 'WKS', 'a well known service description'),
  (1, 12, 'PTR', 'a domain name pointer'),
  (1, 13, 'HINFO', 'host information'),
  (1, 14, 'MINFO', 'mailbox or mail list information'),
  (1, 15, 'MX', 'mail exchange'),
  (1, 16, 'TXT', 'text strings'),
  (1, 17, 'RP', 'for Responsible Person'),
  (1, 18, 'AFSDB', 'for AFS Data Base location'),
  (1, 19, 'X25', 'for X.25 PSDN address'),
  (1, 20, 'ISDN', 'for ISDN address'),
  (1, 21, 'RT', 'for Route Through'),
  (1, 22, 'NSAP', 'for NSAP address, NSAP style A record'),
  (1, 23, 'NSAP-PTR', 'for domain name pointer, NSAP style'),
  (1, 24, 'SIG', 'for security signature'),
  (1, 25, 'KEY', 'for security key'),
  (2, 25, 'KEY', 'for security key'),
  (1, 26, 'PX', 'fX.400 mail mapping information'),
  (1, 27, 'GPOS', 'Geographical Position'),
  (1, 28, 'AAAA', 'IP6 Address'),
  (1, 29, 'LOC', 'Location Information'),
  (1, 30, 'NXT', 'Next Domain (OBSOLETE)'),
  (1, 31, 'EID', 'Endpoint Identifier'),
  (1, 32, 'NIMLOC', 'Nimrod Locator'),
  (1, 33, 'SRV', 'Server Selection'),
  (1, 34, 'ATMA', 'ATM Address'),
  (1, 35, 'NAPTR', 'Naming Authority Pointer'),
  (1, 36, 'KX', 'Key Exchanger'),
  (1, 37, 'CERT', 'CERT'),
  (1, 38, 'A6', 'A6 (OBSOLETE - use AAAA)'),
  (1, 39, 'DNAME', 'DNAME'),
  (1, 40, 'SINK', 'SINK'),
  (1, 41, 'OPT', 'OPT'),
  (1, 42, 'APL', 'APL'),
  (1, 43, 'DS', 'Delegation Signer'),
  (2, 43, 'DS', 'Delegation Signer'),
  (1, 44, 'SSHFP', 'SSH Key Fingerprint'),
  (1, 45, 'IPSECKEY', 'IPSECKEY'),
  (1, 46, 'RRSIG', 'RRSIG'),
  (2, 46, 'RRSIG', 'RRSIG'),
  (1, 47, 'NSEC', 'NSEC'),
  (2, 47, 'NSEC', 'NSEC'),
  (1, 48, 'DNSKEY', 'DNSKEY'),
  (2, 48, 'DNSKEY', 'DNSKEY'),
  (1, 49, 'DHCID', 'DHCID'),
  (1, 50, 'NSEC3', 'NSEC3'),
  (2, 50, 'NSEC3', 'NSEC3'),
  (1, 51, 'NSEC3PARAM', 'NSEC3PARAM'),
  (2, 51, 'NSEC3PARAM', 'NSEC3PARAM'),
  (1, 52, 'TLSA', 'TLSA'),
  (1, 55, 'HIP', 'Host Identity Protocol'),
  (1, 56, 'NINFO', 'NINFO'),
  (1, 57, 'RKEY', 'RKEY'),
  (1, 58, 'TALINK', 'Trust Anchor LINK'),
  (1, 59, 'CDS', 'Child DS'),
  (1, 99, 'SPF', 'SPF'),
  (1, 100, 'UINFO', 'UINFO'),
  (1, 101, 'UID', 'UID'),
  (1, 102, 'GID', 'GID'),
  (1, 103, 'UNSPEC', 'UNSPEC'),
  (1, 104, 'NID', 'NID'),
  (1, 105, 'L32', 'L32'),
  (1, 106, 'L64', 'L64'),
  (1, 107, 'LP', 'LP'),
  (1, 249, 'TKEY', 'Transaction Key'),
  (1, 250, 'TSIG', 'Transaction Signature'),
  (1, 251, 'IXFR', 'incremental transfer'),
  (1, 252, 'AXFR', 'transfer of an entire zone'),
  (1, 253, 'MAILB', 'mailbox-related RRs (MB, MG or MR)'),
  (1, 254, 'MAILA', 'mail agent RRs (OBSOLETE - see MX)'),
  (1, 255, 'ANY', 'A request for all records'),
  (1, 256, 'URI', 'URI'),
  (1, 257, 'CAA', 'Certification Authority Authorization'),
  (1, 32768, 'TA', 'DNSSEC Trust Authorities'),
  (1, 32769, 'DLV', 'DNSSEC Lookaside Validation'),
  (1, 65535, 'Reserved', 'Reserved'),
  (5, 0, 'Query', 'Query'),
  (5, 1, 'IQuery', 'Inverse Query, OBSOLETE'),
  (5, 2, 'Status', 'Status'),
  (5, 3, 'Unassigned', 'Unassigned'),
  (5, 4, 'Notify', 'Notify'),
  (5, 5, 'Update', 'Update'),
  (6, 0, 'NoError', 'No Error'),
  (6, 1, 'FormErr', 'Format Error'),
  (6, 2, 'ServFail', 'Server Failure'),
  (6, 3, 'NXDomain', 'Non-Existent Domain'),
  (6, 4, 'NotImp', 'Not Implemented'),
  (6, 5, 'Refused', 'Query Refused'),
  (6, 6, 'YXDomain', 'Name Exists when it should not'),
  (6, 7, 'YXRRSet', 'RR Set Exists when it should not'),
  (6, 8, 'NXRRSet', 'RR Set that should exist does not'),
  (6, 9, 'NotAuth', 'Server Not Authoritative for zone'),
  (6, 10, 'NotZone', 'Name not contained in zone'),
  (6, 16, 'BADVERS', 'Bad OPT Version'),
  (6, 17, 'BADKEY', 'Key not recognized'),
  (6, 18, 'BADTIME', 'Signature out of time window'),
  (6, 19, 'BADMODE', 'Bad TKEY Mode'),
  (6, 20, 'BADNAME', 'Duplicate key name'),
  (6, 21, 'BADALG', 'Algorithm not supported'),
  (6, 22, 'BADTRUNC', 'Bad Truncation'),
  (6, 65535, 'Reserved', 'Reserved, can be allocated by Standards Action'),
  (7, 0, 'Reserved', 'Reserved'),
  (7, 1, 'LLQ', 'On-hold'),
  (7, 2, 'UL', 'On-hold'),
  (7, 3, 'NSID', 'Standard'),
  (7, 4, 'Reserved', 'Reserved');
